{
 "title": "Business KPI",
 "time": { "from": "now-5y", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Year",
    "label": "Year",
    "query": "SELECT DISTINCT YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) AS year\nFROM global_superstore\nORDER BY year;\n"
   },
   {
    "name": "Country",
    "label": "Country",
    "query": "SELECT CONCAT(\"'\", Country, \"'\") FROM dashboarddb.global_superstore ORDER BY Country\n"
   },
   {
    "name": "Region",
    "label": "Region",
    "query": "SELECT CONCAT(\"'\", Region, \"'\") FROM dashboarddb.global_superstore ORDER BY Region"
   },
   {
    "name": "Market",
    "label": "Market",
    "query": "SELECT CONCAT(\"'\", Market, \"'\") FROM dashboarddb.global_superstore ORDER BY Market"
   },
   {
    "name": "Category",
    "label": "Category",
    "query": "SELECT CONCAT(\"'\", Category, \"'\") FROM dashboarddb.global_superstore ORDER BY Category"
   },
   {
    "name": "Subcategory",
    "label": "Subcategory",
    "query": "SELECT CONCAT(\"'\", Sub_Category, \"'\") FROM dashboarddb.global_superstore ORDER BY Sub_Category"
   }
  ]
 },
 "panels": [
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT COUNT(DISTINCT(Order_ID)) AS \"Total Orders\"\r\nFROM dashboarddb.global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\n\r\n\r\n \r\n"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT SUM(Quantity) as \"Total Quantity\" FROM dashboarddb.global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT SUM(Sales) as \"Total Sales\" FROM dashboarddb.global_superstore \r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT SUM(ShippingCost) as \"Total Shipping Cost\" FROM dashboarddb.global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})"
    }
   ]
  },
  {
   "title": "Sales by Month",
   "type": "barchart",
   "description": "(Last 12 Months Data)",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT\r\n  DATE_FORMAT(STR_TO_DATE(Order_Date, '%Y-%m-%d'), '%b %Y') AS month_label,\r\n  SUM(Sales) AS total_sales,\r\n  DATE_FORMAT(STR_TO_DATE(Order_Date, '%Y-%m-%d'), '%Y-%m') AS sort_key\r\nFROM global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\nGROUP BY month_label, sort_key\r\nORDER BY sort_key desc\r\nlimit 12\r\n"
    }
   ]
  },
  {
   "title": "Sales by Segment",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT\r\n  distinct(Segment) as segment,\r\n  SUM(Sales) AS total_sales\r\nFROM global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\nGROUP BY Segment\r\nORDER BY Segment asc\r\n\r\n"
    }
   ]
  },
  {
   "title": "Sales by Year",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 9, "x": 7, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT\r\n   CONCAT(YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d'))) as year_data,\r\n  SUM(Sales) AS total_sales\r\nFROM global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\nGROUP BY year_data\r\n\r\n"
    }
   ]
  },
  {
   "title": "Sales by Category",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT\r\n  distinct(Category) as category,\r\n  SUM(Sales) AS total_sales\r\nFROM global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\nGROUP BY category\r\nORDER BY category asc\r\n\r\n"
    }
   ]
  },
  {
   "title": "Sales by Top 10 Region",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT\r\n  distinct(Region) as Region,\r\n  SUM(Sales) AS total_sales\r\nFROM global_superstore\r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\nGROUP BY Region\r\nORDER BY total_sales desc\r\nlimit 10\r\n\r\n"
    }
   ]
  },
  {
   "title": "Top 10 Products by Sales",
   "type": "table",
   "gridPos": { "h": 21, "w": 11, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT Product_Name, SUM(Sales) as TotalSales \r\nFROM global_superstore \r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\n    GROUP BY Product_Name ORDER BY TotalSales DESC LIMIT 10"
    }
   ]
  },
  {
   "title": "Top 10 CustomerID by Sales",
   "type": "table",
   "gridPos": { "h": 21, "w": 13, "x": 11, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "dataset": "dashboarddb",
     "rawSql": "SELECT Customer_ID, SUM(Sales) as TotalSales, count(*) as Order_Count\r\nFROM global_superstore \r\nWHERE \r\n  YEAR(STR_TO_DATE(Order_Date, '%Y-%m-%d')) IN (${Year:csv})\r\n    AND Country IN (${Country:csv:singlequote})\r\n    AND Region IN (${Region:csv:singlequote})\r\n    AND Market IN (${Market:csv:singlequote})\r\n    AND Category IN (${Category:csv:singlequote})\r\n    AND Sub_Category IN (${Subcategory:csv:singlequote})\r\n    GROUP BY Customer_ID ORDER BY TotalSales DESC LIMIT 10"
    }
   ]
  }
 ]
}